version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: pierreedouardchaix/udacity-c3-reverseproxy
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: pierreedouardchaix/udacity-c3-restapi-user
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed  
    image: pierreedouardchaix/udacity-c3-restapi-feed  
  frontend:
    build:
      context: ../../udacity-c3-frontend
    image: pierreedouardchaix/udacity-c3-frontend
